### PR TITLE
[WIP] Refactoring and Improvements

### PR DESCRIPTION
**Pull request by bastilian**
I started working on refactoring `middleman-thumbnailer` to make it more flexible and ultimately add generating thumbnails for blog images or essentially all images present in a directory tree and add an `:exclude` option to add limitations.

It is a complete rewrite. There are now `Extension`, `Thumbnails`, `Asset` to cleaner implement initiating and processing images. `Helper` is only cleaned up a bit.

`Rack` is going to be refactored as well to remove `ThumbnailGenerator` and use `Thumbnails` instead.

For #12 I added specs for the rack middleware, which is going to be refactored as well, and will add an integration test.

I'll also take some time to improve the feature specs to not need +10s to run and refactor them.

### CODE REVIEW

**Comment by nhemsley** [comment]
Hey Sebastian,

Hey, sounds good, however I currently don't have time to review this (looks like alot).

Is this a project you would think of taking over? I havent looked in the code for a year or so, and I am out of the loop & busy with other things. I am not on github much any more, so it will probably be easier for anyone hacking on it actively to take over so as not to wait for me to reply etc.

Otherwise I will have a quick look, and basically just merge, and do a major bump, and notify via the readme that it is a new (untested version).

Cheers

**Comment by bastilian** [comment]
Hej nhemsley,

I was thinking of taking this over, in this case.

Would you want to transfer the repository to my account?
This would be the best, I think, so I can add stuff like travis testing and other tools.
All Gemfiles requiring the repository will continue to work (see https://help.github.com/articles/transferring-a-repository/)

**Comment by nhemsley** [comment]
OK I'm happy to transfer it to your account, and I will let you run with it, and merge your changes.

I will keep the original repository for bundles linking to the repo, and update the readme to point to your account.

You will need to rename your bastilian/middleman-thumbnailer repository though, as it will not let me do it currently (it wont do it over an existant repo). Once you have done that, let me know and I will transfer it over.

Thanks for looking into this, and taking it forward!

**Comment by bastilian** [comment]
Awesome! Happy to take it over. I renamed the repo you should be able not to transfer it!

Thank you for starting it and for letting me take care of it!

**Comment by nhemsley** [comment]
Hrm,

Just tried transferring, and it is telling me

`bastilian already has a repository in the nhemsley/middleman-thumbnailer network`

So I guess it knows you already have _that_ repository forked. If you do a  fresh clone and fetch all branches from your repo, and then delete it? This should make sure you dont lose anything youve done.

Or I could just put an EOL notice on my repo for now, but I have a feeling that will cause pain down the track.

Cheers

**Comment by bastilian** [comment]
I pulled the repo off my account let's see if that does the trick. :)

**Comment by nhemsley** [comment]
OK, that seemed to do the trick.

**Comment by bastilian** [comment]
Yes. :D awesome!

Perfect. I'll take it from here. :)

**Comment by nhemsley** [comment]
Alright, cheers & good luck!

**Pull request closed without merging**
